# Generated by Django 3.0.5 on 2022-05-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.BooleanField(default=True, verbose_name='Activada/Desactivada')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('thumbnail', models.URLField(max_length=510, verbose_name='Thumbnail')),
                ('status', models.BooleanField(default=True, verbose_name='Activada/Desactivada')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.CategoriaCurso')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'leccion',
                'verbose_name_plural': 'lecciones',
            },
        ),
        migrations.CreateModel(
            name='SubCategoriaCurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('status', models.BooleanField(default=True, verbose_name='Activada/Desactivada')),
            ],
            options={
                'verbose_name': 'subcategoria',
                'verbose_name_plural': 'subcategorias',
            },
        ),
        migrations.CreateModel(
            name='TypeSlide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('identifier', models.CharField(max_length=100, verbose_name='Identificador')),
            ],
            options={
                'verbose_name': 'ztype_slide',
                'verbose_name_plural': 'ztype_slides',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.Curso')),
            ],
            options={
                'verbose_name': 'tema',
                'verbose_name_plural': 'temas',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('content', models.TextField(blank=True, max_length=255, verbose_name='Parrafo')),
                ('url', models.URLField(blank=True, max_length=510, verbose_name='Imagen/Video')),
                ('code', models.TextField(blank=True, max_length=10000, verbose_name='Código')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.TypeSlide')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.Leccion')),
            ],
            options={
                'verbose_name': 'slide',
                'verbose_name_plural': 'slides',
            },
        ),
        migrations.AddField(
            model_name='leccion',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.Tema'),
        ),
        migrations.AddField(
            model_name='curso',
            name='subcategorias',
            field=models.ManyToManyField(to='CursosApp.SubCategoriaCurso'),
        ),
    ]
