# Generated by Django 3.0.5 on 2022-05-13 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SandboxApp', '0001_initial'),
        ('CursosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(blank=True, max_length=510, verbose_name='Código Ejemplo')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SandboxApp.Language')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.Leccion')),
            ],
            options={
                'verbose_name': 'codigo',
                'verbose_name_plural': 'codigos',
                'ordering': ['-createdAt'],
            },
        ),
    ]
